name: localpdb
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Set environment
      run: |
        echo "::set-env name=PYTHONPATH::/home/runner/work/localpdb/localpdb"
    - name: Test with pytest
      run: |
        pytest --cov-report=xml --cov=localpdb -v
    - name: Codecov
      if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false