name: localpdb
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install requirements.txt
    - name: Test with pytest
      run: |
        echo "::set-env name=PYTHONPATH::home/runner/work/labstructbioinf/localpdb"
        pytest --cov=localpdb -v
    - name: coveralls
      if: ${{ matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest' }}
      uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}